name: Run unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/migrate-archive-keyring.gpg
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test